djkarmap/api/urls.py
from django.urls import path
from . views import JobApiView, JobDetailView

urlpatterns = [
    path('job_search/<int:group>/<int:user_type>/',  JobApiView.as_view()),
    path('job/<int:pk>/', JobDetailView.as_view()),
]

djkarmap/djkarmap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')), 
    path('api/', include('api.urls')),   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djkarmap/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):

    EMPLOYEE = 'KJ'
    EMPLOYER = 'KF'
    USER_TYPE_CHOICES = [
        (EMPLOYEE, 'کارجو'),
        (EMPLOYER, 'کارفرما'),
    ]

    user_type = models.CharField(choices=USER_TYPE_CHOICES, default=EMPLOYEE, max_length=10)

    def __str__(self):
        return self.username

djkarmap/main_app/models.py
from django.contrib.gis.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.urls import reverse

from main_app.choices import GENDER_CHOICES, EDUCATION_CHOICES


class JobGroup(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Employee(models.Model):
    """ 
        ForignKey==>
        This means that a given user can be the author of many different blog posts
        but not the other way around.
    """
    user = models.OneToOneField(
        get_user_model(), on_delete=models.CASCADE
    )
    # phoneNumber = == >
    gender = models.CharField(choices=GENDER_CHOICES,
                              max_length=20, blank=True, null=True)

    birth_date = models.DateField(blank=True, null=True)
    education = models.CharField(
        max_length=25,
        blank=True,
        choices=EDUCATION_CHOICES,
    )
    thumb = models.ImageField(default= 'default-thumb.jpeg', upload_to='employee/thumb', blank=True)
    is_active = models.BooleanField(default=True)
    last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    image = models.ImageField(default='default.jpg',
                              blank=True, upload_to='employee')

    location = models.PointField(srid=4326, blank=True, null=True)

    def __str__(self):
        return self.user.email

    def save(self, *args, **kwargs):
        from main_app.utils import generate_thumbnail
        self.thumb = generate_thumbnail(self.image)
        super(Employee, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        from main_app.utils import delete_from_s3
        delete_from_s3([self.image, self.thumb])
        super(Employee, self).delete(*args, **kwargs)


class Employer(models.Model):
    user = models.OneToOneField(
        get_user_model(), on_delete=models.CASCADE
    )
    location = models.PointField(srid=4326, blank=True, null=True)
    employer_type = models.CharField(choices=(
        ('person', 'Person'), ('company', 'Company'),), max_length=20, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.user.email


class Job(models.Model):

    JOB_TYPE = (
        (1, "تمام وقت"),
        (2, "پاره وقت"),
        (3, "پروژه‌ای"),
        (4, "کارآموزی"),
        (5, "توافقی"),
        (6, "سایر"),
    )
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    group = models.ForeignKey(JobGroup, on_delete=models.CASCADE)
    location = models.PointField(srid=4326, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('job_detail', args=[f'{self.id}'])


class JobOrder(models.Model):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE
    )

    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return f'{self.user}: {self.created.__str__()}'

djkarmap/templates/profile/employee_display_info_tab.html
<!-- its equal hasattr(request.user, 'employee') mean user complete profile info -->
 {% if request.user.employee %}
<div class="card testimonial-card">
    <!--Background color-->
    <div class="card-up info-color"></div>
    <!--Avatar-->
    <div class="avatar mx-auto white">
    <img src="{{ request.user.employee.image.url }}" class="rounded-circle img-fluid">
    </div>
    <div class="card-body">
    <!--Name-->
    <h4 class="font-weight-bold mb-4">{{ user.get_full_name }}</h4>
    <hr>
    <!--Quotation-->
    <p class="dark-grey-text mt-4"><i class="fa fa-quote-left pr-2"></i>
        علاقه مند به آموزش فناوریهای مکانی
    </p>

    <p> {{ user.get_full_name }} </p>

    <p> {{ user.get_user_type_display }}</p>

    <p> {{ user.employee.get_gender_display }} </p>
    <p> {{ user.employee.get_education_display }} </p>
    <p> {{ user.employee.image.url }} </p>
    <p> {{ user.employee.birth_date }}</p>
    <p> {{ user.employee.location }} </p>

  
    </div>



</div>
<!--Card-->        
 {% else %}
    <p> {{ request.user.get_full_name }}: </p>
   <p> ابتدا مشخصاتخود را تکمیل کنید. </p>
  
 {% endif %}









 <!-- Horizontal Steppers -->
<div class="row">
  <div class="col-md-12">

    <!-- Stepers Wrapper -->
    <ul class="stepper stepper-horizontal">

      <!-- First Step -->
      <li class="completed">
        <a href="#!">
          <span class="circle">1</span>
          <span class="label">First step</span>
        </a>
      </li>

      <!-- Second Step -->
      <li class="active">
        <a href="#!">
          <span class="circle">2</span>
          <span class="label">Second step</span>
        </a>
      </li>

      <!-- Third Step -->
      <li class="warning">
        <a href="#!">
          <span class="circle"><i class="fas fa-exclamation"></i></span>
          <span class="label">Third step</span>
        </a>
      </li>

    </ul>
    <!-- /.Stepers Wrapper -->

  </div>
</div>
<!-- /.Horizontal Steppers -->


    

djkarmap/templates/profile/employee_form.html
{% load crispy_forms_tags %}

{% if request.user.employee %}

<p> اطلاعات قبلا تکمیل شده بنابراین لازم نیست فیلدها نمایش داده شوند </p>

{% else %}

<div class="container">
  <div class="row">
    <form id="employee_info" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-info">ذخیره اطلاعات</button>
    </form>
  </div>
</div>

{% endif %}



  

djkarmap/templates/profile/employee_order_tab.html
<br>
<h1></h1>
<hr>
{% for near_job_order in nearest_jobs_order %}
<div class="card">
    <div class="card-header">
        <span class="font-weight-bold">{{ near_job_order.job }}</span> |
        <span class="text-muted"> توسط {{ near_job_order.user }}  |
            {{ near_job_order.created|timesince }}</span>|
    </div>
    <div class="card-body">
        {{ near_job_order.job }}
    </div>
    <div class="card-footer text-center text-muted">
        <a href="#">نمایش روی نقشه</a> | <a href="#">مشاهده جزئیات و درخواست</a>
    </div>    
</div>
<br>
{% empty %}
    <li>متاسفانه هنوز درخواستی در سیستم ثبت نشده است</li>
<br />

{% endfor %}

djkarmap/templates/profile/profile.html
{% extends 'base.html' %}


{% block extra_head %}  
      <!-- for displaying map form in template -->
      {{ form.media }}
{% endblock %}

{% block content %}

<div class="container">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home"
            aria-selected="true">تکمیل مشخصات</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile"
            aria-selected="false">مشاهده اطلاعات</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact"
            aria-selected="false">درخواست</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            {% include "profile/employee_form.html" %}
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">          
            {% include "profile/employee_display_info_tab.html" %}
        </div>
        <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
            {% include "profile/employee_order_tab.html" %}  
        </div>
      </div>
</div> 


{% endblock %}


{% block exterascriptend %}
  {{ block.super }}
  {% include "profile/profile_scripts.html" %}
{% endblock %}

djkarmap/templates/profile/profile_scripts.html
<script>
    $('.datepicker').pickadate();

</script>